//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleBooksNE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleBooksNE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Audios.
        /// </summary>
        internal static string Audios {
            get {
                return ResourceManager.GetString("Audios", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        internal static string Document
        {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        internal static string DocumentPage
        {
            get {
                return ResourceManager.GetString("DocumentPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        internal static string Hungarian {
            get {
                return ResourceManager.GetString("Hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Database Directory.
        /// </summary>
        internal static string AlternativeDatabaseDirectory {
            get {
                return ResourceManager.GetString("AlternativeDatabaseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Program Home Directory.
        /// </summary>
        internal static string AlternativeProgramHomeDirectory {
            get {
                return ResourceManager.GetString("AlternativeProgramHomeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Resources Directory.
        /// </summary>
        internal static string AlternativeResourcesDirectory {
            get {
                return ResourceManager.GetString("AlternativeResourcesDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Directory.
        /// </summary>
        internal static string BaseDirectory {
            get {
                return ResourceManager.GetString("BaseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon BibleBooksNE_Icon {
            get {
                object obj = ResourceManager.GetObject("BibleBooksNE_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BibleBooksNE_Picture {
            get {
                object obj = ResourceManager.GetObject("BibleBooksNE_Picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible information.
        /// </summary>
        internal static string BibleInformation {
            get {
                return ResourceManager.GetString("BibleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bible Parts.
        /// </summary>
        internal static string BibleParts {
            get {
                return ResourceManager.GetString("BibleParts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bible Part Page.
        /// </summary>
        internal static string BiblePartPage
        {
            get {
                return ResourceManager.GetString("BiblePartsPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search result page.
        /// </summary>
        internal static string SearchResultPage
        {
            get {
                return ResourceManager.GetString("SearchResultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibles.
        /// </summary>
        internal static string Bibles {
            get {
                return ResourceManager.GetString("Bibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Names.
        /// </summary>
        internal static string BookNames {
            get {
                return ResourceManager.GetString("BookNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Parts.
        /// </summary>
        internal static string BookParts {
            get {
                return ResourceManager.GetString("BookParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log.
        /// </summary>
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter Parts.
        /// </summary>
        internal static string ChapterParts {
            get {
                return ResourceManager.GetString("ChapterParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        internal static string Chapters {
            get {
                return ResourceManager.GetString("Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters.
        /// </summary>
        internal static string Counters {
            get {
                return ResourceManager.GetString("Counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosslinks.
        /// </summary>
        internal static string Crosslinks {
            get {
                return ResourceManager.GetString("Crosslinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Information.
        /// </summary>
        internal static string DatabaseInformation {
            get {
                return ResourceManager.GetString("DatabaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database reading error..
        /// </summary>
        internal static string DatabaseReadingError {
            get {
                return ResourceManager.GetString("DatabaseReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        internal static string Databases {
            get {
                return ResourceManager.GetString("Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database subdirectory not exist!.
        /// </summary>
        internal static string DatabaseSubDirNotExist {
            get {
                return ResourceManager.GetString("DatabaseSubDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database was not found..
        /// </summary>
        internal static string DatabaseWasNotFound {
            get {
                return ResourceManager.GetString("DatabaseWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Database Directory.
        /// </summary>
        internal static string DefaultDatabaseDirectory {
            get {
                return ResourceManager.GetString("DefaultDatabaseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Program Home Directory.
        /// </summary>
        internal static string DefaultProgramHomeDirectory {
            get {
                return ResourceManager.GetString("DefaultProgramHomeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Resources Directory.
        /// </summary>
        internal static string DefaultResourcesDirectory {
            get {
                return ResourceManager.GetString("DefaultResourcesDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory name.
        /// </summary>
        internal static string DirectoryName {
            get {
                return ResourceManager.GetString("DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... .
        /// </summary>
        internal static string MessagesEmptyHtmlFileTemplate
        {
            get {
                return ResourceManager.GetString("MessagesEmptyHtmlFileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in navigation!.
        /// </summary>
        internal static string ErrorInNavigation {
            get {
                return ResourceManager.GetString("ErrorInNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not valid..
        /// </summary>
        internal static string FileIsNotValid {
            get {
                return ResourceManager.GetString("FileIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file not exist..
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reading error..
        /// </summary>
        internal static string FileReadingError {
            get {
                return ResourceManager.GetString("FileReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to open.
        /// </summary>
        internal static string FilesToOpen {
            get {
                return ResourceManager.GetString("FilesToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File writing error..
        /// </summary>
        internal static string FileWritingError {
            get {
                return ResourceManager.GetString("FileWritingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saving error..
        /// </summary>
        internal static string FileSavingError {
            get {
                return ResourceManager.GetString("FileSavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footnotes.
        /// </summary>
        internal static string Footnotes {
            get {
                return ResourceManager.GetString("Footnotes", resourceCulture);
            }
        }
        

        
        /// <summary>
        ///   Looks up a localized string similar to Generated by.
        /// </summary>
        internal static string GeneratedBy {
            get {
                return ResourceManager.GetString("GeneratedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headlines.
        /// </summary>
        internal static string Headlines {
            get {
                return ResourceManager.GetString("Headlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headlines.
        /// </summary>
        internal static string HeadlineMatches {
            get {
                return ResourceManager.GetString("HeadlineMatches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VerseMatches.
        /// </summary>
        internal static string VerseMatches {
            get {
                return ResourceManager.GetString("VerseMatches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FootnoteMatches.
        /// </summary>
        internal static string FootnoteMatches {
            get {
                return ResourceManager.GetString("FootnoteMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript runtime error!.
        /// </summary>
        internal static string JavaScriptRuntimeError {
            get {
                return ResourceManager.GetString("JavaScriptRuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        internal static string Justify {
            get {
                return ResourceManager.GetString("Justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long name.
        /// </summary>
        internal static string LongName {
            get {
                return ResourceManager.GetString("LongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markdown file.
        /// </summary>
        internal static string MarkdownFile {
            get {
                return ResourceManager.GetString("MarkdownFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing database name error..
        /// </summary>
        internal static string MissingDatabaseNameError {
            get {
                return ResourceManager.GetString("MissingDatabaseNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi bible mode.
        /// </summary>
        internal static string MultiBibleMode {
            get {
                return ResourceManager.GetString("MultiBibleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No databases!.
        /// </summary>
        internal static string NoDatabases {
            get {
                return ResourceManager.GetString("NoDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches!.
        /// </summary>
        internal static string NoMatches {
            get {
                return ResourceManager.GetString("NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found!.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found any Book item..
        /// </summary>
        internal static string NotFoundAnyBookItem {
            get {
                return ResourceManager.GetString("NotFoundAnyBookItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found any Chapter item..
        /// </summary>
        internal static string NotFoundAnyChapterItem {
            get {
                return ResourceManager.GetString("NotFoundAnyChapterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found any Verse item..
        /// </summary>
        internal static string NotFoundAnyVerseItem {
            get {
                return ResourceManager.GetString("NotFoundAnyVerseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet!.
        /// </summary>
        internal static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only html files.
        /// </summary>
        internal static string OnlyHtmlFiles {
            get {
                return ResourceManager.GetString("OnlyHtmlFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only text files.
        /// </summary>
        internal static string OnlyTextFiles {
            get {
                return ResourceManager.GetString("OnlyTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other file.
        /// </summary>
        internal static string OtherFile {
            get {
                return ResourceManager.GetString("OtherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html file.
        /// </summary>
        internal static string HtmlFile {
            get {
                return ResourceManager.GetString("HtmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string NumberOfMatches {
            get {
                return ResourceManager.GetString("NumberOfMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string NumberOfAllMatches
        {
            get {
                return ResourceManager.GetString("NumberOfAllMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select Book!.
        /// </summary>
        internal static string PleaseSelectBook {
            get {
                return ResourceManager.GetString("PleaseSelectBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select Chapter!.
        /// </summary>
        internal static string PleaseSelectChapter {
            get {
                return ResourceManager.GetString("PleaseSelectChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select one or more Bible without 0!.
        /// </summary>
        internal static string PleaseSelectOneOrMoreBibleWithoutZero {
            get {
                return ResourceManager.GetString("PleaseSelectOneOrMoreBibleWithoutZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select Verse!.
        /// </summary>
        internal static string PleaseSelectVerse {
            get {
                return ResourceManager.GetString("PleaseSelectVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Directories.
        /// </summary>
        internal static string ProgramDirectories {
            get {
                return ResourceManager.GetString("ProgramDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question!.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader Style.
        /// </summary>
        internal static string ReaderStyle {
            get {
                return ResourceManager.GetString("ReaderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searched text.
        /// </summary>
        internal static string SearchedText {
            get {
                return ResourceManager.GetString("SearchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection!.
        /// </summary>
        internal static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Text Page.
        /// </summary>
        internal static string SimpleTextPage {
            get {
                return ResourceManager.GetString("SimpleTextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single bible mode.
        /// </summary>
        internal static string SingleBibleMode {
            get {
                return ResourceManager.GetString("SingleBibleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong!.
        /// </summary>
        internal static string SorrySomethingWentWrong {
            get {
                return ResourceManager.GetString("SorrySomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source url.
        /// </summary>
        internal static string SourceUrl {
            get {
                return ResourceManager.GetString("SourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template resource file access error..
        /// </summary>
        internal static string TemplateResourceFileAccessError {
            get {
                return ResourceManager.GetString("TemplateResourceFileAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test is finished!.
        /// </summary>
        internal static string TestIsFinished {
            get {
                return ResourceManager.GetString("TestIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file.
        /// </summary>
        internal static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows inserted/updated affected by it:.
        /// </summary>
        internal static string TheNumberOfRowsInserted_UpdatedAffectedByIt {
            get {
                return ResourceManager.GetString("TheNumberOfRowsInserted/UpdatedAffectedByIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Action Page.
        /// </summary>
        internal static string UserActionPage {
            get {
                return ResourceManager.GetString("UserActionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Database Directory.
        /// </summary>
        internal static string UserDatabaseDirectory {
            get {
                return ResourceManager.GetString("UserDatabaseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Document Directory.
        /// </summary>
        internal static string UserDocuments {
            get {
                return ResourceManager.GetString("UserDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Home Directory.
        /// </summary>
        internal static string UserHomeDirectory {
            get {
                return ResourceManager.GetString("UserHomeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Resources Directory.
        /// </summary>
        internal static string UserResourcesDirectory {
            get {
                return ResourceManager.GetString("UserResourcesDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verses.
        /// </summary>
        internal static string Verses {
            get {
                return ResourceManager.GetString("Verses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        

        internal static string MessagesScript
        {
            get {
                return ResourceManager.GetString("MessagesScript", resourceCulture);
            }
        }
        

        internal static string MessagesStyle
        {
            get {
                return ResourceManager.GetString("MessagesStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to BibleBooks!.
        /// </summary>
        internal static string WelcomeToBibleBooks {
            get {
                return ResourceManager.GetString("WelcomeToBibleBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordsList.
        /// </summary>
        internal static string WordsList {
            get {
                return ResourceManager.GetString("WordsList", resourceCulture);
            }
        }

        internal static string VersesHtmlFileTemplate_FirstPart
        {
            get {
                return ResourceManager.GetString("VersesHtmlFileTemplate_FirstPart", resourceCulture);
            }
        }
        internal static string VersesHtmlFileTemplate_SecondPart
        {
            get {
                return ResourceManager.GetString("VersesHtmlFileTemplate_SecondPart", resourceCulture);
            }
        }
        internal static string VersesHtmlFileTemplate_ThirdPart
        {
            get {
                return ResourceManager.GetString("VersesHtmlFileTemplate_ThirdPart", resourceCulture);
            }
        }

        public static string FileNameIsNotValid
        {
            get
            {
                return ResourceManager.GetString("FileNameIsNotValid", resourceCulture);
            }
        }

        public static string HelpFileNotFound
        {
            get
            {
                return ResourceManager.GetString("HelpFileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Help File For BBNE.
        /// </summary>
        internal static string HelpFileForBBNE
        {
            get
            {
                return ResourceManager.GetString("HelpFileForBBNE", resourceCulture);
            }
        }

    }
}
