<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>BibleBooksNE_Icon.ico</ApplicationIcon>
	<AssemblyName>BibleBooksNE</AssemblyName>
	<ProductName>BibleBooks New Edition</ProductName>
    <Authors>Zsolt Lőrincz</Authors>
    <PublisherName>Zsolt Lőrincz</PublisherName>
    <PackageIcon>BibleBooksNE_Picture.png</PackageIcon>
    <Copyright>Zsolt Lőrin©z</Copyright>
    <Description>Bible Reader program for MS Windows.</Description>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="TMP\**" />
    <EmbeddedResource Remove="TMP\**" />
    <None Remove="TMP\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="BibleBooksNE_Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Help\HelpFileForBBNE_EN.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Help\HelpFileForBBNE_HU.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\BibleBooksNE_Picture.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>